### ISSUE TITLE
rpmbuild found buildroot in installed files error

### ISSUE THREAD

**Issue by ghost** [kevinconway/rpmvenv#24] opened 2015-11-12 09:42 UTC
Hi,
I am not sure if this problem is related to rpmvenv, maybe more with rpmbuild.
When I run rpmvenv <path-to-json-file>,
it fails with the following RPM build error:
<--
Found '/tmp/rpmvenvEUnH5a/BUILDROOT/mypkg-3.1-1.x86_64' in installed files; aborting
-->

Also setting the following env. var.  before running rpmvenv seems to fix th problem:
export QA_SKIP_BUILD_ROOT=1

My config:
CentOS Linux release 7.1.1503 (Core)

**Comment by kevinconway** [comment] 2015-11-12 11:54
Do you mind posting the JSON config or set of flags you're using when generating the rpm?

Also, thanks for opening an issue!

**Comment by jripsl** [comment] 2015-11-12 12:56
JSON config file:
<---
{
    "extensions": {
        "enabled": [
            "python_venv",
            "blocks"
        ]
    },
    "core": {
        "group": "Application/System",
        "license": "MIT",
        "name": "mypkg",
        "summary": "myrpmpkg",
        "version": "3.1"
    },
    "python_venv": {
        "name": "sdt",
        "path": "/usr/share/python",
        "flags": []
    },
    "blocks": {
        "desc": [
            "some long package description",
            "each array element is a new line"
        ]
    }
}
--->

Command used:
rpmvenv /home/centos/garbage/synda/sdt/mypkg.json

Project:
git clone https://github.com/Prodiguer/synda.git
cd synda/sdt

**Comment by kevinconway** [comment] 2015-11-12 13:24
Excellent, thanks for the steps to reproduce. I'll see if I can trigger the same error you are seeing. In the meantime you may be able to work around the path issue by running `rpmvenv` from outside the source directory.

```shell
git clone https://github.com/Prodiguer/synda.git
rpmvenv /home/centos/synda/sdt/mypkg.json --source synda/sdt
```

**Comment by kevinconway** [comment] 2015-11-20 03:05
FYI, I'm having some trouble reproducing the error. Using the example config and running the `rpmvenv` command from within the repo generated an RPM without exception.

Did using the `--source` flag help any or are you still experiencing the issue?

**Comment by jripsl** [comment] 2015-11-25 08:54
I made some progress: I did the same test using another distrib (Fedora release 21) and now it works. So it seems that the problem is specific to the Centos 7.1 and/or 'rpm-build' version.
On Fedora, rpm-build version is 4.12.0.1
On Centos, rpm-build version is 4.11.1
Anyway, now my problem is solved as I don't have any requirement regarding the package build platform, i.e. if it works on fedora, I will use fedora as the build platform.

> Did using the --source flag help any or are you still experiencing the issue?

Nop, I have the same error using the --source flag

I will now try to make the rpm package install a systemd daemon as my application run in the background.

Thanks for your help

**Comment by kevinconway** [comment] 2015-12-01 01:06
I'm glad you were able to find a workaround. I'm going to keep the issue open until I have a chance to reproduce it. If it ends up being a certain version or version range of rpmbuild I'll probably close the issue and document the exceptions.

I really appreciate you letting me know about the bug. Please open another issue if you hit something else.

**Comment by jbremond** [comment] 2016-01-12 17:56
Hello,
I have the same error than jripsl, and I can reproduced it on my Fedora 21 last updated.
The rpmbuild version is:
```
rpmbuild --version 
RPM version 4.12.0.1
```

My json file is the following:
```
{
    "extensions": {
        "enabled": [
            "python_venv",
            "blocks"
        ]
    },
    "core": {
        "group": "Application/System",
        "license": "Apache V2",
        "name": "my",
        "summary": "my package summary",
        "version": "1.0"
    },
    "python_venv": {
        "name": "name_of_venv_dir_to_create",
        "path": "/tmp/my-autoenv",
        "flags": [""]
    },
    "blocks": {
        "desc": [
            "some long package description",
            "each array element is a new line"
        ]
    }
}
```

If I read the rpm spec file, I found this:
```
....
venvctrl-relocate --source=%{venv_dir} --destination=/%{venv_install_dir}
%prep
....
```
It fails in the prep step.
The prep step normally do this (according to http://www.rpm.org/max-rpm/s1-rpm-inside-scripts.html):
- Create the top-level build directory.
- Unpack the original sources into the build directory.
- Apply patches to the sources, if necessary.
- Perform any other actions required to get the sources in a ready-to-build state. 

and the venvctrl-relocate command launched just before already create the "build directory".
I think the issue could be here.

What do you think ?
Do you have a workaround ?

Thanks for your help,
Joris

**Comment by kevinconway** [comment] 2016-01-12 22:54
I've struggled to recreate this error. If you can reliably recreate with Fedora 21 and rpmbuild 12 then I'll give that a shot.

Would you mind running the command with `--verbose ` and pasting the output? It may help give some additional data to work with.

**Comment by jbremond** [comment] 2016-01-13 13:53
Thanks for your response.
I have write a procedure to reproduce the issue:
It is based on a fedora 21 docker image.
please launch these commands:
```
docker pull fedora:21
docker run -t -i fedora:21 /bin/bash
yum install -y python-pip gcc python-devel libxml2-devel libxslt-devel git python-virtualenv rpm-build
pip install rpmvenv
# now, I checkout a python project
git clone https://github.com/usharesoft/hammr.git
cd hammr
git checkout -b hammr-uforge-3.5.1 remotes/origin/hammr-uforge-3.5.1
cd src
```
Now please add the following file into the src directory:
rpm.json:
```

{
    "extensions": {
        "enabled": [
            "python_venv",
            "blocks"
        ]
    },
    "core": {
        "group": "Application/System",
        "license": "Apache V2",
        "name": "my",
        "summary": "my package summary",
        "version": "1.0"
    },
    "python_venv": {
        "name": "name_of_venv_dir_to_create",
        "path": "/tmp/my-autoenv",
        "flags": [""]
    },
    "blocks": {
        "desc": [
            "some long package description",
            "each array element is a new line"
        ]
    }
}
```

and 
requirements.txt:
```
uforge_python_sdk>=3.5.1.3, <3.6
httplib2==0.9
cmd2==0.6.7
texttable>=0.8.1
progressbar==2.3
argparse
paramiko==1.12
pyparsing==2.0.2
hurry.filesize==0.9
termcolor==1.1.0
junit-xml==1.3
xmlrunner==1.7.7
```
 and launch:
```
rpmvenv rpm.json --verbose
```

I get the following error:

```
...
...
Using /tmp/rpmvenvy6gwH8/BUILDROOT/my-1.0-1.x86_64/tmp/my-autoenv/name_of_venv_dir_to_create/lib/python2.7/site-packages
Finished processing dependencies for hammr==0.2.5.9
+ cd -
/tmp/rpmvenvy6gwH8/BUILD
+ find /tmp/rpmvenvy6gwH8/BUILDROOT/my-1.0-1.x86_64 -name RECORD -exec rm -rf '{}' ';'
+ venvctrl-relocate --source=/tmp/rpmvenvy6gwH8/BUILDROOT/my-1.0-1.x86_64//tmp/my-autoenv/name_of_venv_dir_to_create --destination=//tmp/my-autoenv/name_of_venv_dir_to_create
+ /usr/lib/rpm/check-buildroot
/tmp/rpmvenvy6gwH8/BUILDROOT/my-1.0-1.x86_64/tmp/my-autoenv/name_of_venv_dir_to_create/lib/python2.7/site-packages/setuptools.pth:/tmp/rpmvenvy6gwH8/BUILDROOT/my-1.0-1.x86_64/tmp/my-autoenv/name_of_venv_dir_to_create/lib/python2.7/site-packages
/tmp/rpmvenvy6gwH8/BUILDROOT/my-1.0-1.x86_64/tmp/my-autoenv/name_of_venv_dir_to_create/lib/python2.7/site-packages/hammr-0.2.5.9-py2.7.egg/EGG-INFO/scripts/hammr:#!/tmp/rpmvenvy6gwH8/BUILDROOT/my-1.0-1.x86_64/tmp/my-autoenv/name_of_venv_dir_to_create/bin/python
Found '/tmp/rpmvenvy6gwH8/BUILDROOT/my-1.0-1.x86_64' in installed files; aborting
error: Bad exit status from /var/tmp/rpm-tmp.yiDwWI (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.yiDwWI (%install)
There was an error generating the RPM.
The exit code was: 1.
The rpmbuild command was: rpmbuild -ba --define='_topdir /tmp/rpmvenvy6gwH8' /tmp/rpmvenvy6gwH8/SOURCES/package.spec.
```

Thanks for your help

Regards,
Joris

**Comment by jripsl** [comment] 2016-01-17 13:50
Hi,

I just reproduce the error with vagrant vm "hansode/fedora-21-server-x86_64" for "hammr" github project.
Also there is no error with "Synda" github project and fedora21.

Meaning the error is be project dependant.


Also error occurs with  "Synda" github project and centos 7.1.
On Fedora, rpm-build version is 4.12.0.1
On Centos, rpm-build version is 4.11.1

Meaning the error is OS / rpm-build version dependant.


I retrieved rpmbuild source using
wget http://rpm.org/releases/rpm-4.12.x/rpm-4.12.0.1.tar.bz2

A grep of "installed files" into rpmbuild 4.12.0.1 source match this file
=> rpm-4.12.0.1/scripts/check-buildroot


Code below trigger the "installed files" msg

```
find "$RPM_BUILD_ROOT" \! \( \
    -name '*.pyo' -o -name '*.pyc' -o -name '*.elc' -o -name '.packlist' \
    \) -type f -print0 | \
    LANG=C xargs -0r grep -F "$RPM_BUILD_ROOT" >$tmp
```

**Comment by kevinconway** [comment] 2016-01-17 17:41
Thank you both for posting so much useful debugging info.

I'm still attempting to narrow down why you are seeing this behaviour only on certain packages or certain versions of rpm-build. However, I _do_ believe this should be considered a bug for the `venvctrl` project I made to support moving the virtual environments around. It appears as though the check-buildroot script is looking at the text in every file to see if the BUILDROOT directory is mentioned. One of the `.pth` files in `site-packages` currently contains an entry that refers to the directory it is in which is inside the BUILDROOT. The `venvctrl` project is supposed to rewrite paths like this one but does not currently address `.pth` files. I believe adding support for `.pth` file re-writes would resolve this issue.

I will continue to investigate why this only happens sometimes and work on scheduling time to fix the `venvctrl` project. In the meantime, I suggest using the environment variable that @jripsl mentioned, `QA_SKIP_BUILD_ROOT=1 rpmvenv <path_to_config>`, to disable this check. For the projects you both have mentioned, the `.pth` file is the _only_ file that contains the bad path so disabling the check should not have a negative impact.

**Comment by jbremond** [comment] 2016-01-28 10:53
Thanks for the workaround, it works very well with
```
QA_SKIP_BUILD_ROOT=1 rpmvenv <path_to_config>
```

Regards,
Joris

**Comment by sharksforarms** [comment] 2017-10-20 12:45
Any updates on this issue?

**Comment by kevinconway** [comment] 2017-10-25 02:01
Unfortunately, no. I haven't resolved this issue yet. This ticket fell out of sight, out of mind for me. I never did file the bug for `venvctrl` to track the resolution. I've created a new bug for venvctrl here: https://github.com/kevinconway/venvctrl/issues/3.

Now that I'm reminded of the issue, I'd like to close it. I'll try to schedule some time this weekend to finish up the work in `venvctrl`.

**Comment by kevinconway** [comment] 2019-08-25 04:46
For anyone still watching this issue:

Since my last update the following have completed:

- Long form shebangs are handled thanks to @tlusk 
- .pth files are now processed to inject the correct paths
- The new .xsh activation script is rewritten if it exists
- https://github.com/pypa/manylinux/issues/78 has closed which should have resolved issues related to binaries having metadata that couldn't be removed via `strip`.

As far as I know, those are all of the various causes for getting the "<buildroot> in installed files" errors. I'm going to close this long standing issue under the assumption that all of the issues have been resolved. Please open new issues for any new or recurring cases of stale path related errors if you have them.

**Closed by kevinconway** 2019-08-25 04:46 UTC
