### ISSUE TITLE
Stripping libraries fails. (CentOS 7)

### ISSUE THREAD

**Issue by Neurocinetics** [kevinconway/rpmvenv#48] opened 2017-02-01 14:22 UTC
Dear Kevin,

It seems that libraries (.so) cannot be reliably stripped:
135: `'find %{venv_dir}/lib -type f -name "*.so" | xargs -r strip'` 

Returns: 

> Not enough room for program headers, try linking with -N

I tried editing it into this:
135: `'find %{venv_dir}/lib -type f -name "*.so" | xargs -r -0 strip'`

Returns: 

> Warning: could not locate....reason: File name too long (_pylibmc.cpython-34m.so for example)

135: `'find %{venv_dir}/lib -type f -name "*.so" -print0 | xargs -r -0 strip'`

Also fails:
> Not enough room for program headers, try linking with -N

What would be a proper way to tackle this? Should we temporarily disable the stripping of libraries?
Might be related to: #https://github.com/pypa/manylinux/issues/78 and #https://github.com/NixOS/patchelf/issues/10.

Regards,

Neurocinetics

**Comment by kevinconway** [comment] 2017-02-22 02:01
Hrm... OK. Do you have an example project you can point me to that reliably recreates this issue? I'd like to narrow down which packages and/or versions of Python are affected.

**Comment by mikhtonyuk** [comment] 2017-03-03 22:07
We have encountered the same issue. It seems to happen when stripping any `.so` file built with manylinux.

I have created a project that reproduces this issue using the publicly-available `cffi` package that has manylinux wheel distribution: https://github.com/mikhtonyuk/rpmvenv_issue

We have tried the [WIP proposed solution](https://github.com/NixOS/patchelf/compare/master...staticfloat:sf/pr_10) mentioned on NixOS/patchelf#10, it fixed stripping issue but breaks library import:
```
ImportError: /usr/lib64/python2.7/site-packages/***.so: ELF load command address/offset not properly aligned
```

Taking a step back though, why do we need stripping as part of `rpmvenv` packaging process? In case of wheel packages I would expect the wheel to already contain a stripped binary, so this step is not necessary. For libraries build from source stripping is also something that belongs to the build process.

**Comment by kevinconway** [comment] 2017-03-05 01:32
For the details on why we added a call to `strip`, take a look at #31 .The short version is that native modules often contain the build path in their metadata. This causes `rpm` to fail because it will not allow the build path to be referenced from within the package. 

As far as a fix, it will be more complicated than disabling the call to `strip`. I am not against making the call to `strip` optional so long as the default option is enabled for backwards compatibility with existing users. However, even if we add an option to disable the call to `strip` there is no (officially) documented way of disabling the buildroot-check when generating an rpm. When the check runs it will cause the rpm build to fail because it will find references to the buildroot in the native modules. The only way we've found to handle this other than `strip` is to use an internal `QA_SKIP_BUILD_ROOT=1` environment variable to disable the check.

I'm of the opinion that it is the manylinux project's responsibility to generate binaries that work with standard tools like `strip`. As you've both pointed out there are bugs posted for them that we can track until they are closed. In the meantime, does it sound like a reasonable approach to 1) make `strip` optional with a default option of enabled and 2) add the `QA_SKIP_BUILD_ROOT=1` environment variable to your build environments in order to suppress the check?

If so, when I get a chance I'll use the repo @mikhtonyuk posted to verify this actuallly work.

**Comment by mikhtonyuk** [comment] 2017-03-06 19:21
Thanks for the details, @kevinconway. 

We have also ran into issue #24 with one of our packages, so we are already using `QA_SKIP_BUILD_ROOT=1` in our builds.

For all of our intents and purposes making `strip` optional should be enough, and will give us a nice workaround until the root cause of this issue is fixed in binutils.

**Comment by mikhtonyuk** [comment] 2017-03-06 19:42
Created a PR #51 for adding the config option. @kevinconway please take a look and see if you can release it any time soon. I'd love to avoid maintaining our own patched version of `rpmvenv`.

**Comment by Neurocinetics** [comment] 2017-03-06 21:51
Dear Kevin,

Yes, I agree that we can't remove the stripping procedure. You could indeed (temporarily) make stripping optional, having it enabled by default. And the environment variable: QA_SKIP_BUILD_ROOT seems temporarily sufficient. For now I guess we can wait on binutils to get fixed. 

Did the [fix](https://github.com/staticfloat/patchelf/commit/7f6fcb43f6db63a6dd53629a894e6a97787104b4#diff-ecd3d9ea3a7bedb9da1146861deba89eR683) staticfloat proposed work for you?

Dear Sergii,

Thank you for providing a reproducible environment and for your thoughts on the matter.

Regards,

Neurocinetics

**Comment by kevinconway** [comment] 2017-03-09 02:36
@mikhtonyuk take a look at #53 

I've cherry-picked your commit over into a branch where I've added tests for the issue to verify the fix. I cloned the sample repo you gave and added that as a test case. I'll get it merged and released before late tomorrow.

**Comment by kevinconway** [comment] 2017-03-09 18:59
Hi folks. I've merged the patch and regression tests. The changes are now live on PyPi as version 0.16.0.

**Closed by kevinconway** 2017-03-09 18:59 UTC
